### ISSUE TITLE
Error KY/Madison - Andrea

### ISSUE THREAD

**Issue by public-safety-lab** [public-safety-lab/JDI#1]

**Comment by public-safety-lab** [comment]
[ec2-user@ip-172-31-88-82 Madison]$ python Madison.py
********** SCRAPE INFORMATION **********

Today's Date:   2019-06-26
State:          KY
County:         Madison
Facility Name:  Madison County Detention Center
State Code:     18
Jail ID:        1173

****************************************

Executing scrape...
Traceback (most recent call last):
  File "Madison.py", line 111, in <module>
    scraper.run()
  File "../../_Generic_Classes/SuperScraper.py", line 406, in run
    self.inmate_data = self.scrape()
  File "Madison.py", line 96, in scrape
    all_inmates.append(self.parseHTML(source_code))
  File "Madison.py", line 52, in parseHTML
    d['Name'] = self.merge_name(d['First_Name'], d['Middle_Name'], d['Last_Name'], d['Suffix'])
TypeError: merge_name() takes 4 positional arguments but 5 were given

**Comment by public-safety-lab** [comment]
the output is thrown on the terminal, rest seems fine. If its in CSV we'll be able to check it better.

**Comment by public-safety-lab** [comment]
********** SCRAPE INFORMATION **********

Today's Date:   2019-07-03
State:          KY
County:         Madison
Facility Name:  Madison County Detention Center
State Code:     18
Jail ID:        1173

****************************************

Executing scrape...
Traceback (most recent call last):
  File "../../_Generic_Classes/JailTracker.py", line 82, in scrape
    npages = self.npages
AttributeError: 'JailTrackerScraper' object has no attribute 'npages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Madison.py", line 32, in <module>
    scraper.run()
  File "../../_Generic_Classes/SuperScraper.py", line 448, in run
    self.inmate_data = self.scrape()
  File "../../_Generic_Classes/JailTracker.py", line 84, in scrape
    npages = int(self.driver.find_elements_by_class_name('xtb-text')[1].text.split()[-1])
IndexError: list index out of range

**Comment by andrea-w-wang** [comment]
fixed.
